/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FindAllWalletTransactionsRequest {
    /**
     * Number of page
     */
    page?: number;
    /**
     * Number of records per page
     */
    perPage?: number;
    /**
     * Status (pending or settled)
     */
    status?: string;
    /**
     * Transaction Type (inbound or outbound)
     */
    transactionType?: string;
}
