/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Invoices: core.serialization.ObjectSchema<serializers.Invoices.Raw, LagoApi.Invoices> =
    core.serialization.object({
        invoices: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).InvoiceObject))
            .optional(),
    });

export declare namespace Invoices {
    interface Raw {
        invoices?: serializers.InvoiceObject.Raw[] | null;
    }
}
