/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Invoice: core.serialization.ObjectSchema<serializers.Invoice.Raw, LagoApi.Invoice> =
    core.serialization.object({
        invoice: core.serialization.lazyObject(async () => (await import("../../..")).InvoiceObject).optional(),
    });

export declare namespace Invoice {
    interface Raw {
        invoice?: serializers.InvoiceObject.Raw | null;
    }
}
