/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const InvoiceStatus: core.serialization.Schema<serializers.InvoiceStatus.Raw, LagoApi.InvoiceStatus> =
    core.serialization.enum_(["draft", "finalized"]);

export declare namespace InvoiceStatus {
    type Raw = "draft" | "finalized";
}
