/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface AppliedCouponInputObject {
    externalCustomerId?: string;
    couponCode?: string;
    frequency?: LagoApi.FrequencyType;
    frequencyDuration?: number;
    amountCents?: number;
    amountCurrency?: string;
    percentageRate?: number;
}
