/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CouponStatus = "active" | "terminated";

export const CouponStatus = {
    Active: "active",
    Terminated: "terminated",
} as const;
