/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CouponType = "fixed_amount" | "percentage";

export const CouponType = {
    FixedAmount: "fixed_amount",
    Percentage: "percentage",
} as const;
