/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface CouponInputObject {
    name?: string;
    code?: string;
    couponType?: LagoApi.CouponType;
    amountCents?: number;
    amountCurrency?: string;
    reusable?: boolean;
    percentageRate?: number;
    frequency?: LagoApi.FrequencyType;
    frequencyDuration?: number;
    expirationAt?: string;
    expiration?: LagoApi.ExpirationType;
}
