/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ExpirationType = "no_expiration" | "time_limit";

export const ExpirationType = {
    NoExpiration: "no_expiration",
    TimeLimit: "time_limit",
} as const;
