/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FrequencyType = "once" | "recurring";

export const FrequencyType = {
    Once: "once",
    Recurring: "recurring",
} as const;
