/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CreditStatus: core.serialization.Schema<serializers.CreditStatus.Raw, LagoApi.CreditStatus> =
    core.serialization.enum_(["available", "consumed", "voided"]);

export declare namespace CreditStatus {
    type Raw = "available" | "consumed" | "voided";
}
