/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CreditNoteObject: core.serialization.ObjectSchema<
    serializers.CreditNoteObject.Raw,
    LagoApi.CreditNoteObject
> = core.serialization.object({
    lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
    sequentialId: core.serialization.property("sequential_id", core.serialization.number().optional()),
    number: core.serialization.string().optional(),
    lagoInvoiceId: core.serialization.property("lago_invoice_id", core.serialization.string().optional()),
    invoiceNumber: core.serialization.property("invoice_number", core.serialization.string().optional()),
    issuingDate: core.serialization.property("issuing_date", core.serialization.string().optional()),
    creditStatus: core.serialization.property(
        "credit_status",
        core.serialization.lazy(async () => (await import("../../..")).CreditStatus).optional()
    ),
    refundStatus: core.serialization.property(
        "refund_status",
        core.serialization.lazy(async () => (await import("../../..")).RefundStatus).optional()
    ),
    reason: core.serialization.lazy(async () => (await import("../../..")).CreditReason).optional(),
    description: core.serialization.string().optional(),
    totalAmountCents: core.serialization.property("total_amount_cents", core.serialization.number().optional()),
    totalAmountCurrency: core.serialization.property("total_amount_currency", core.serialization.string().optional()),
    vatAmountCents: core.serialization.property("vat_amount_cents", core.serialization.number().optional()),
    vatAmountCurrency: core.serialization.property("vat_amount_currency", core.serialization.string().optional()),
    subTotalVatExcludedAmountCents: core.serialization.property(
        "sub_total_vat_excluded_amount_cents",
        core.serialization.number().optional()
    ),
    subTotalVatExcludedAmountCurrency: core.serialization.property(
        "sub_total_vat_excluded_amount_currency",
        core.serialization.string().optional()
    ),
    balanceAmountCents: core.serialization.property("balance_amount_cents", core.serialization.number().optional()),
    balanceAmountCurrency: core.serialization.property(
        "balance_amount_currency",
        core.serialization.string().optional()
    ),
    creditAmountCents: core.serialization.property("credit_amount_cents", core.serialization.number().optional()),
    creditAmountCurrency: core.serialization.property("credit_amount_currency", core.serialization.string().optional()),
    refundAmountCents: core.serialization.property("refund_amount_cents", core.serialization.number().optional()),
    refundAmountCurrency: core.serialization.property("refund_amount_currency", core.serialization.string().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.string().optional()),
    fileUrl: core.serialization.property("file_url", core.serialization.string().optional()),
    customer: core.serialization.lazyObject(async () => (await import("../../..")).CustomerObject).optional(),
    items: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).CreditNoteItemObject))
        .optional(),
});

export declare namespace CreditNoteObject {
    interface Raw {
        lago_id?: string | null;
        sequential_id?: number | null;
        number?: string | null;
        lago_invoice_id?: string | null;
        invoice_number?: string | null;
        issuing_date?: string | null;
        credit_status?: serializers.CreditStatus.Raw | null;
        refund_status?: serializers.RefundStatus.Raw | null;
        reason?: serializers.CreditReason.Raw | null;
        description?: string | null;
        total_amount_cents?: number | null;
        total_amount_currency?: string | null;
        vat_amount_cents?: number | null;
        vat_amount_currency?: string | null;
        sub_total_vat_excluded_amount_cents?: number | null;
        sub_total_vat_excluded_amount_currency?: string | null;
        balance_amount_cents?: number | null;
        balance_amount_currency?: string | null;
        credit_amount_cents?: number | null;
        credit_amount_currency?: string | null;
        refund_amount_cents?: number | null;
        refund_amount_currency?: string | null;
        created_at?: string | null;
        updated_at?: string | null;
        file_url?: string | null;
        customer?: serializers.CustomerObject.Raw | null;
        items?: serializers.CreditNoteItemObject.Raw[] | null;
    }
}
