/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CreditNoteItem: core.serialization.ObjectSchema<serializers.CreditNoteItem.Raw, LagoApi.CreditNoteItem> =
    core.serialization.object({
        feeId: core.serialization.property("fee_id", core.serialization.string().optional()),
        amountCents: core.serialization.property("amount_cents", core.serialization.number().optional()),
    });

export declare namespace CreditNoteItem {
    interface Raw {
        fee_id?: string | null;
        amount_cents?: number | null;
    }
}
