/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CreditNoteUpdateInput: core.serialization.ObjectSchema<
    serializers.CreditNoteUpdateInput.Raw,
    LagoApi.CreditNoteUpdateInput
> = core.serialization.object({
    creditNote: core.serialization.property(
        "credit_note",
        core.serialization.lazyObject(async () => (await import("../../..")).CreditNoteInputObject).optional()
    ),
});

export declare namespace CreditNoteUpdateInput {
    interface Raw {
        credit_note?: serializers.CreditNoteInputObject.Raw | null;
    }
}
