/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CreditNote: core.serialization.ObjectSchema<serializers.CreditNote.Raw, LagoApi.CreditNote> =
    core.serialization.object({
        creditNote: core.serialization.property(
            "credit_note",
            core.serialization.lazyObject(async () => (await import("../../..")).CreditNoteObject).optional()
        ),
    });

export declare namespace CreditNote {
    interface Raw {
        credit_note?: serializers.CreditNoteObject.Raw | null;
    }
}
