/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TransactionStatus = "pending" | "settled";

export const TransactionStatus = {
    Pending: "pending",
    Settled: "settled",
} as const;
