/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WalletStatus = "active" | "terminated";

export const WalletStatus = {
    Active: "active",
    Terminated: "terminated",
} as const;
