/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface WalletObject {
    lagoId?: string;
    lagoCustomerId?: string;
    externalCustomerId?: string;
    status?: LagoApi.WalletStatus;
    currency?: string;
    name?: string;
    rateAmount?: number;
    creditsBalance?: number;
    balance?: number;
    consumedCredits?: number;
    createdAt?: string;
    expirationAt?: string;
    lastBalanceSyncAt?: string;
    lastConsumedCreditAt?: string;
    terminatedAt?: string;
}
