/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WalletInputObject {
    name?: string;
    rateAmount?: number;
    currency?: string;
    paidCredits?: number;
    grantedCredits?: number;
    externalCustomerId?: string;
    expirationAt?: string;
}
