/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface WalletTransactionObject {
    lagoId?: string;
    lagoWalletId?: string;
    status?: LagoApi.TransactionStatus;
    transactionType?: LagoApi.TransactionType;
    amount?: number;
    creditAmount?: number;
    settledAt?: string;
    createdAt?: string;
}
