/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WalletTransactionInputObject {
    walletId?: string;
    paidCredits?: number;
    grantedCredits?: number;
}
