/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BatchEventInputObject {
    transactionId?: string;
    externalCustomerId?: string;
    code?: string;
    timestamp?: number;
    externalSubscriptionIds?: string[];
    properties?: Record<string, unknown>;
}
