/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EventObject {
    lagoId?: string;
    transactionId?: string;
    lagoCustomerId?: string;
    externalCustomerId?: string;
    code?: string;
    timestamp?: string;
    properties?: Record<string, unknown>;
    lagoSubscriptionId?: string;
    externalSubscriptionId?: string;
    createdAt?: string;
}
