/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EventInputObject {
    transactionId?: string;
    externalCustomerId?: string;
    code?: string;
    timestamp?: number;
    externalSubscriptionId?: string;
    properties?: Record<string, unknown>;
}
