/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const SubscriptionStatus: core.serialization.Schema<
    serializers.SubscriptionStatus.Raw,
    LagoApi.SubscriptionStatus
> = core.serialization.enum_(["active", "pending", "terminated", "canceled"]);

export declare namespace SubscriptionStatus {
    type Raw = "active" | "pending" | "terminated" | "canceled";
}
