/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const SubscriptionUpdateInput: core.serialization.ObjectSchema<
    serializers.SubscriptionUpdateInput.Raw,
    LagoApi.SubscriptionUpdateInput
> = core.serialization.object({
    subscription: core.serialization
        .lazyObject(async () => (await import("../../..")).SubscriptionUpdateInputObject)
        .optional(),
});

export declare namespace SubscriptionUpdateInput {
    interface Raw {
        subscription?: serializers.SubscriptionUpdateInputObject.Raw | null;
    }
}
