/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Subscription: core.serialization.ObjectSchema<serializers.Subscription.Raw, LagoApi.Subscription> =
    core.serialization.object({
        subscription: core.serialization
            .lazyObject(async () => (await import("../../..")).SubscriptionObject)
            .optional(),
    });

export declare namespace Subscription {
    interface Raw {
        subscription?: serializers.SubscriptionObject.Raw | null;
    }
}
