/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Subscriptions: core.serialization.ObjectSchema<serializers.Subscriptions.Raw, LagoApi.Subscriptions> =
    core.serialization.object({
        subscriptions: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).SubscriptionObject))
            .optional(),
    });

export declare namespace Subscriptions {
    interface Raw {
        subscriptions?: serializers.SubscriptionObject.Raw[] | null;
    }
}
