/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const SubscriptionUpdateInputObject: core.serialization.ObjectSchema<
    serializers.SubscriptionUpdateInputObject.Raw,
    LagoApi.SubscriptionUpdateInputObject
> = core.serialization.object({
    name: core.serialization.string().optional(),
    subscriptionAt: core.serialization.property("subscription_at", core.serialization.string().optional()),
});

export declare namespace SubscriptionUpdateInputObject {
    interface Raw {
        name?: string | null;
        subscription_at?: string | null;
    }
}
