/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const BillingConfigurationOrganization: core.serialization.ObjectSchema<
    serializers.BillingConfigurationOrganization.Raw,
    LagoApi.BillingConfigurationOrganization
> = core.serialization.object({
    invoiceFooter: core.serialization.property("invoice_footer", core.serialization.string().optional()),
    invoiceGracePeriod: core.serialization.property("invoice_grace_period", core.serialization.number().optional()),
    vatRate: core.serialization.property("vat_rate", core.serialization.number().optional()),
});

export declare namespace BillingConfigurationOrganization {
    interface Raw {
        invoice_footer?: string | null;
        invoice_grace_period?: number | null;
        vat_rate?: number | null;
    }
}
