/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Organization: core.serialization.ObjectSchema<serializers.Organization.Raw, LagoApi.Organization> =
    core.serialization.object({
        organization: core.serialization
            .lazyObject(async () => (await import("../../..")).OrganizationObject)
            .optional(),
    });

export declare namespace Organization {
    interface Raw {
        organization?: serializers.OrganizationObject.Raw | null;
    }
}
