/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const OrganizationInput: core.serialization.ObjectSchema<
    serializers.OrganizationInput.Raw,
    LagoApi.OrganizationInput
> = core.serialization.object({
    organization: core.serialization
        .lazyObject(async () => (await import("../../..")).OrganizationInputObject)
        .optional(),
});

export declare namespace OrganizationInput {
    interface Raw {
        organization?: serializers.OrganizationInputObject.Raw | null;
    }
}
