/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const BatchEventInput: core.serialization.ObjectSchema<
    serializers.BatchEventInput.Raw,
    LagoApi.BatchEventInput
> = core.serialization.object({
    event: core.serialization.lazyObject(async () => (await import("../../..")).BatchEventInputObject).optional(),
});

export declare namespace BatchEventInput {
    interface Raw {
        event?: serializers.BatchEventInputObject.Raw | null;
    }
}
