/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const EventInput: core.serialization.ObjectSchema<serializers.EventInput.Raw, LagoApi.EventInput> =
    core.serialization.object({
        event: core.serialization.lazyObject(async () => (await import("../../..")).EventInputObject).optional(),
    });

export declare namespace EventInput {
    interface Raw {
        event?: serializers.EventInputObject.Raw | null;
    }
}
