/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const EventObject: core.serialization.ObjectSchema<serializers.EventObject.Raw, LagoApi.EventObject> =
    core.serialization.object({
        lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
        transactionId: core.serialization.property("transaction_id", core.serialization.string().optional()),
        lagoCustomerId: core.serialization.property("lago_customer_id", core.serialization.string().optional()),
        externalCustomerId: core.serialization.property("external_customer_id", core.serialization.string().optional()),
        code: core.serialization.string().optional(),
        timestamp: core.serialization.string().optional(),
        properties: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        lagoSubscriptionId: core.serialization.property("lago_subscription_id", core.serialization.string().optional()),
        externalSubscriptionId: core.serialization.property(
            "external_subscription_id",
            core.serialization.string().optional()
        ),
        createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    });

export declare namespace EventObject {
    interface Raw {
        lago_id?: string | null;
        transaction_id?: string | null;
        lago_customer_id?: string | null;
        external_customer_id?: string | null;
        code?: string | null;
        timestamp?: string | null;
        properties?: Record<string, unknown> | null;
        lago_subscription_id?: string | null;
        external_subscription_id?: string | null;
        created_at?: string | null;
    }
}
