/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const EventInputObject: core.serialization.ObjectSchema<
    serializers.EventInputObject.Raw,
    LagoApi.EventInputObject
> = core.serialization.object({
    transactionId: core.serialization.property("transaction_id", core.serialization.string().optional()),
    externalCustomerId: core.serialization.property("external_customer_id", core.serialization.string().optional()),
    code: core.serialization.string().optional(),
    timestamp: core.serialization.number().optional(),
    externalSubscriptionId: core.serialization.property(
        "external_subscription_id",
        core.serialization.string().optional()
    ),
    properties: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace EventInputObject {
    interface Raw {
        transaction_id?: string | null;
        external_customer_id?: string | null;
        code?: string | null;
        timestamp?: number | null;
        external_subscription_id?: string | null;
        properties?: Record<string, unknown> | null;
    }
}
