/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Event: core.serialization.ObjectSchema<serializers.Event.Raw, LagoApi.Event> = core.serialization.object({
    event: core.serialization.lazyObject(async () => (await import("../../..")).EventObject).optional(),
});

export declare namespace Event {
    interface Raw {
        event?: serializers.EventObject.Raw | null;
    }
}
