/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class LagoApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, LagoApiTimeoutError.prototype);
    }
}
