/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

/**
 * @example
 *     {
 *         addOn: {
 *             name: "add_on_name",
 *             code: "add_on_code",
 *             amountCents: 5000,
 *             amountCurrency: "USD",
 *             description: "desc"
 *         }
 *     }
 */
export interface AddOnInput {
    addOn?: LagoApi.AddOnInputObject;
}
