/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "add_on_name",
 *         code: "add_on_code",
 *         amountCents: 5000,
 *         amountCurrency: "USD",
 *         description: "desc"
 *     }
 */
export interface AddOnInputObject {
    name?: string;
    code?: string;
    description?: string;
    amountCents?: number;
    amountCurrency?: string;
}
