/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AddOnInputObject {
    name?: string;
    code?: string;
    description?: string;
    amountCents?: number;
    amountCurrency?: string;
}
