/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         lagoId: "b7ab2926-1de8-4428-9bcd-779314ac129b",
 *         name: "add_on_name",
 *         code: "add_on_code",
 *         amountCents: 5000,
 *         amountCurrency: "USD",
 *         description: "description",
 *         createdAt: "2022-04-29T08:59:51Z"
 *     }
 */
export interface AddOnObject {
    lagoId?: string;
    name?: string;
    code?: string;
    description?: string;
    createdAt?: string;
    amountCents?: number;
    amountCurrency?: string;
}
