/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AddOnObject {
    lagoId?: string;
    name?: string;
    code?: string;
    description?: string;
    createdAt?: string;
    amountCents?: number;
    amountCurrency?: string;
}
