/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         externalCustomerId: "5eb02857-a71e-4ea2-bcf9-57d3a41bc6ba",
 *         addOnCode: "code",
 *         amountCents: 123,
 *         amountCurrency: "EUR"
 *     }
 */
export interface AppliedAddOnInputObject {
    externalCustomerId?: string;
    addOnCode?: string;
    amountCents?: number;
    amountCurrency?: string;
}
