/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppliedAddOnInputObject {
    externalCustomerId?: string;
    addOnCode?: string;
    amountCents?: number;
    amountCurrency?: string;
}
