/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppliedAddOnObject {
    lagoId?: string;
    lagoAddOnId?: string;
    addOnCode?: string;
    lagoCustomerId?: string;
    externalCustomerId?: string;
    amountCents?: number;
    amountCurrency?: string;
    createdAt?: string;
}
