/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const ChargeModelType: core.serialization.Schema<serializers.ChargeModelType.Raw, LagoApi.ChargeModelType> =
    core.serialization.enum_(["standard", "graduated", "package", "percentage", "volume"]);

export declare namespace ChargeModelType {
    type Raw = "standard" | "graduated" | "package" | "percentage" | "volume";
}
