/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const ChargeBillableMetric: core.serialization.ObjectSchema<
    serializers.ChargeBillableMetric.Raw,
    LagoApi.ChargeBillableMetric
> = core.serialization.object({
    lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
    name: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
    aggregationType: core.serialization.property(
        "aggregation_type",
        core.serialization.lazy(async () => (await import("../../..")).AggregationType).optional()
    ),
});

export declare namespace ChargeBillableMetric {
    interface Raw {
        lago_id?: string | null;
        name?: string | null;
        code?: string | null;
        aggregation_type?: serializers.AggregationType.Raw | null;
    }
}
