/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CustomerInput: core.serialization.ObjectSchema<serializers.CustomerInput.Raw, LagoApi.CustomerInput> =
    core.serialization.object({
        customer: core.serialization.lazyObject(async () => (await import("../../..")).CustomerInputObject).optional(),
    });

export declare namespace CustomerInput {
    interface Raw {
        customer?: serializers.CustomerInputObject.Raw | null;
    }
}
