/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const BillableMetrics: core.serialization.ObjectSchema<
    serializers.BillableMetrics.Raw,
    LagoApi.BillableMetrics
> = core.serialization.object({
    billableMetrics: core.serialization.property(
        "billable_metrics",
        core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).BillableMetricObject))
            .optional()
    ),
});

export declare namespace BillableMetrics {
    interface Raw {
        billable_metrics?: serializers.BillableMetricObject.Raw[] | null;
    }
}
