/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const BillableMetricInputObject: core.serialization.ObjectSchema<
    serializers.BillableMetricInputObject.Raw,
    LagoApi.BillableMetricInputObject
> = core.serialization.object({
    name: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    fieldName: core.serialization.property("field_name", core.serialization.string().optional()),
    aggregationType: core.serialization.property(
        "aggregation_type",
        core.serialization.lazy(async () => (await import("../../..")).AggregationType).optional()
    ),
    group: core.serialization.lazyObject(async () => (await import("../../..")).BillableMetricGroup).optional(),
});

export declare namespace BillableMetricInputObject {
    interface Raw {
        name?: string | null;
        code?: string | null;
        description?: string | null;
        field_name?: string | null;
        aggregation_type?: serializers.AggregationType.Raw | null;
        group?: serializers.BillableMetricGroup.Raw | null;
    }
}
