/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const GroupObject: core.serialization.ObjectSchema<serializers.GroupObject.Raw, LagoApi.GroupObject> =
    core.serialization.object({
        key: core.serialization.string().optional(),
        value: core.serialization.string().optional(),
        lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
    });

export declare namespace GroupObject {
    interface Raw {
        key?: string | null;
        value?: string | null;
        lago_id?: string | null;
    }
}
