/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Groups: core.serialization.ObjectSchema<serializers.Groups.Raw, LagoApi.Groups> =
    core.serialization.object({
        groups: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).GroupObject))
            .optional(),
    });

export declare namespace Groups {
    interface Raw {
        groups?: serializers.GroupObject.Raw[] | null;
    }
}
