/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../../core";

export const ApplyAddOnInput: core.serialization.Schema<serializers.ApplyAddOnInput.Raw, LagoApi.ApplyAddOnInput> =
    core.serialization.object({
        appliedAddOn: core.serialization.property(
            "applied_add_on",
            core.serialization.lazyObject(async () => (await import("../../../..")).AppliedAddOnInputObject).optional()
        ),
    });

export declare namespace ApplyAddOnInput {
    interface Raw {
        applied_add_on?: serializers.AppliedAddOnInputObject.Raw | null;
    }
}
