/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface OrganizationInputObject {
    webhookUrl?: string;
    country?: string;
    addressLine1?: string;
    addressLine2?: string;
    state?: string;
    zipode?: string;
    email?: string;
    city?: string;
    legalName?: string;
    legalNumber?: string;
    timezone?: string;
    billingConfiguration?: LagoApi.BillingConfigurationOrganization;
}
