/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FindAllAddOnsInput {
    /**
     * Number of page
     */
    page?: number;
    /**
     * Number of records per page
     */
    perPage?: number;
}
