/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreditReason =
    | "duplicated_charge"
    | "product_unsatisfactory"
    | "order_change"
    | "order_cancellation"
    | "fraudulent_charge"
    | "other";

export const CreditReason = {
    DuplicatedCharge: "duplicated_charge",
    ProductUnsatisfactory: "product_unsatisfactory",
    OrderChange: "order_change",
    OrderCancellation: "order_cancellation",
    FraudulentCharge: "fraudulent_charge",
    Other: "other",
} as const;
