/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreditStatus = "available" | "consumed" | "voided";

export const CreditStatus = {
    Available: "available",
    Consumed: "consumed",
    Voided: "voided",
} as const;
