/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface CreditNoteObject {
    lagoId?: string;
    sequentialId?: number;
    number?: string;
    lagoInvoiceId?: string;
    invoiceNumber?: string;
    issuingDate?: string;
    creditStatus?: LagoApi.CreditStatus;
    refundStatus?: LagoApi.RefundStatus;
    reason?: LagoApi.CreditReason;
    description?: string;
    totalAmountCents?: number;
    totalAmountCurrency?: string;
    vatAmountCents?: number;
    vatAmountCurrency?: string;
    subTotalVatExcludedAmountCents?: number;
    subTotalVatExcludedAmountCurrency?: string;
    balanceAmountCents?: number;
    balanceAmountCurrency?: string;
    creditAmountCents?: number;
    creditAmountCurrency?: string;
    refundAmountCents?: number;
    refundAmountCurrency?: string;
    createdAt?: string;
    updatedAt?: string;
    fileUrl?: string;
    customer?: LagoApi.CustomerObject;
    items?: LagoApi.CreditNoteItemObject[];
}
