/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface CreditNoteInputObject {
    invoiceId?: string;
    reason?: LagoApi.CreditNoteReason;
    description?: string;
    creditAmountCents?: number;
    refundAmountCents?: number;
    items?: LagoApi.CreditNoteItem[];
}
