/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface CreditNoteInput {
    creditNote?: LagoApi.CreditNoteInputObject;
}
