/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface ChargeUsageObject {
    units?: number;
    amountCents?: number;
    amountCurrency?: string;
    charge?: LagoApi.Charge;
    billableMetric?: LagoApi.ChargeBillableMetric;
    groups?: LagoApi.Group[];
}
