/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface Charge {
    lagoId?: string;
    /** Charge model type */
    chargeModel?: LagoApi.ChargeModelType;
}
