/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface CustomerUsageObject {
    fromDatetime?: string;
    toDatetime?: string;
    issuingDate?: string;
    amountCents?: number;
    amountCurrency?: string;
    totalAmountCents?: number;
    totalAmountCurrency?: string;
    vatAmountCents?: number;
    vatAmountCurrency?: string;
    chargesUsage?: LagoApi.ChargeUsageObject[];
}
