/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Group {
    lagoId?: string;
    key?: string;
    value?: string;
    units?: number;
    amountCents?: number;
}
