/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InvoiceStatus = "draft" | "finalized";

export const InvoiceStatus = {
    Draft: "draft",
    Finalized: "finalized",
} as const;
