/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface BillableMetricInputObject {
    name?: string;
    code?: string;
    description?: string;
    fieldName?: string;
    aggregationType?: LagoApi.AggregationType;
    group?: LagoApi.BillableMetricGroup;
}
