/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         lagoId: "b7ab2926-1de8-4428-9bcd-779314ac129b",
 *         key: "group_key",
 *         value: "group_value"
 *     }
 */
export interface GroupObject {
    key?: string;
    value?: string;
    lagoId?: string;
}
