/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface FindAllInvoicesRequest {
    /**
     * Number of page
     */
    page?: number;
    /**
     * Number of records per page
     */
    perPage?: number;
    externalCustomerId?: string;
    issuingDateFrom?: string;
    issuingDateTo?: string;
    status?: LagoApi.InvoiceStatus;
}
