/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const TransactionType: core.serialization.Schema<serializers.TransactionType.Raw, LagoApi.TransactionType> =
    core.serialization.enum_(["inbound", "outbound"]);

export declare namespace TransactionType {
    type Raw = "inbound" | "outbound";
}
