/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Wallets: core.serialization.ObjectSchema<serializers.Wallets.Raw, LagoApi.Wallets> =
    core.serialization.object({
        wallets: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).WalletObject))
            .optional(),
    });

export declare namespace Wallets {
    interface Raw {
        wallets?: serializers.WalletObject.Raw[] | null;
    }
}
