/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const WalletUpdateInputObject: core.serialization.ObjectSchema<
    serializers.WalletUpdateInputObject.Raw,
    LagoApi.WalletUpdateInputObject
> = core.serialization.object({
    name: core.serialization.string().optional(),
    expirationAt: core.serialization.property("expiration_at", core.serialization.string().optional()),
});

export declare namespace WalletUpdateInputObject {
    interface Raw {
        name?: string | null;
        expiration_at?: string | null;
    }
}
