/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const WalletUpdateInput: core.serialization.ObjectSchema<
    serializers.WalletUpdateInput.Raw,
    LagoApi.WalletUpdateInput
> = core.serialization.object({
    wallet: core.serialization.lazyObject(async () => (await import("../../..")).WalletUpdateInputObject).optional(),
});

export declare namespace WalletUpdateInput {
    interface Raw {
        wallet?: serializers.WalletUpdateInputObject.Raw | null;
    }
}
