/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FindCustomerCurrentUsageRequest {
    /**
     * External subscription ID
     */
    externalSubscriptionId: string;
}
