/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface ChargeObject {
    lagoId?: string;
    lagoBillableMetricId?: string;
    createdAt?: string;
    chargeModel?: LagoApi.ChargeModelType;
    properties?: Record<string, unknown>;
    groupProperties?: LagoApi.GroupPropertiesObject[];
}
