/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ChargeModel = "standard" | "graduated" | "package" | "percentage" | "volume";

export const ChargeModel = {
    Standard: "standard",
    Graduated: "graduated",
    Package: "package",
    Percentage: "percentage",
    Volume: "volume",
} as const;
