/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface Charges {
    id?: string;
    billableMetricId?: string;
    chargeModel?: LagoApi.ChargeModel;
    properties?: Record<string, unknown>;
    groupProperties?: LagoApi.GroupProperties[];
}
