/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const AddOns: core.serialization.ObjectSchema<serializers.AddOns.Raw, LagoApi.AddOns> =
    core.serialization.object({
        addOns: core.serialization.property(
            "add_ons",
            core.serialization
                .list(core.serialization.lazyObject(async () => (await import("../../..")).AddOnObject))
                .optional()
        ),
    });

export declare namespace AddOns {
    interface Raw {
        add_ons?: serializers.AddOnObject.Raw[] | null;
    }
}
