/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const AppliedAddOn: core.serialization.ObjectSchema<serializers.AppliedAddOn.Raw, LagoApi.AppliedAddOn> =
    core.serialization.object({
        appliedAddOn: core.serialization.property(
            "applied_add_on",
            core.serialization.lazyObject(async () => (await import("../../..")).AppliedAddOnObject).optional()
        ),
    });

export declare namespace AppliedAddOn {
    interface Raw {
        applied_add_on?: serializers.AppliedAddOnObject.Raw | null;
    }
}
