/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const AppliedAddOnInput: core.serialization.ObjectSchema<
    serializers.AppliedAddOnInput.Raw,
    LagoApi.AppliedAddOnInput
> = core.serialization.object({
    appliedAddOn: core.serialization.property(
        "applied_add_on",
        core.serialization.lazyObject(async () => (await import("../../..")).AppliedAddOnInputObject).optional()
    ),
});

export declare namespace AppliedAddOnInput {
    interface Raw {
        applied_add_on?: serializers.AppliedAddOnInputObject.Raw | null;
    }
}
