/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const AppliedAddOnInputObject: core.serialization.ObjectSchema<
    serializers.AppliedAddOnInputObject.Raw,
    LagoApi.AppliedAddOnInputObject
> = core.serialization.object({
    externalCustomerId: core.serialization.property("external_customer_id", core.serialization.string().optional()),
    addOnCode: core.serialization.property("add_on_code", core.serialization.string().optional()),
    amountCents: core.serialization.property("amount_cents", core.serialization.number().optional()),
    amountCurrency: core.serialization.property("amount_currency", core.serialization.string().optional()),
});

export declare namespace AppliedAddOnInputObject {
    interface Raw {
        external_customer_id?: string | null;
        add_on_code?: string | null;
        amount_cents?: number | null;
        amount_currency?: string | null;
    }
}
