/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AggregationType = "count_agg" | "sum_agg" | "max_agg" | "unique_count_agg" | "recurring_count_agg";

export const AggregationType = {
    CountAgg: "count_agg",
    SumAgg: "sum_agg",
    MaxAgg: "max_agg",
    UniqueCountAgg: "unique_count_agg",
    RecurringCountAgg: "recurring_count_agg",
} as const;
