/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface AppliedCouponObject {
    lagoId?: string;
    lagoCouponId?: string;
    couponCode?: string;
    lagoCustomerId?: string;
    externalCustomerId?: string;
    status?: LagoApi.Status;
    amountCents?: number;
    amountCentsRemaining?: number;
    amountCurrency?: string;
    percentageRate?: number;
    frequency?: LagoApi.FrequencyType;
    frequencyDuration?: number;
    frequencyDurationRemaining?: number;
    expirationAt?: string;
    createdAt?: string;
    terminatedAt?: string;
}
