/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface BillableMetricObject {
    lagoId?: string;
    name?: string;
    code?: string;
    description?: string;
    createdAt?: string;
    fieldName?: string;
    aggregationType?: LagoApi.AggregationType;
    group?: LagoApi.BillableMetricGroup;
    activeSubscriptionsCount?: number;
    draftInvoicesCount?: number;
}
