/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BillingTime = "calendar" | "anniversary";

export const BillingTime = {
    Calendar: "calendar",
    Anniversary: "anniversary",
} as const;
