/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ChargeModelType = "standard" | "graduated" | "package" | "percentage" | "volume";

export const ChargeModelType = {
    Standard: "standard",
    Graduated: "graduated",
    Package: "package",
    Percentage: "percentage",
    Volume: "volume",
} as const;
