/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface CreditObject {
    lagoId?: string;
    amountCents?: number;
    amountCurrency?: string;
    item?: LagoApi.CreditItem;
}
