/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface CustomerObject {
    lagoId?: string;
    externalId?: string;
    name?: string;
    sequentialId?: number;
    slug?: string;
    createdAt?: string;
    country?: string;
    addressLine1?: string;
    addressLine2?: string;
    state?: string;
    zipode?: string;
    email?: string;
    city?: string;
    url?: string;
    phone?: string;
    lagoUrl?: string;
    legalName?: string;
    legalNumber?: string;
    currency?: string;
    timezone?: string;
    applicableTimezone?: string;
    billingConfiguration?: LagoApi.BillingConfigurationCustomer;
}
