/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface FeeItem {
    type?: LagoApi.BillingTime;
    code?: string;
    name?: string;
}
