/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface FeeObject {
    lagoId?: string;
    lagoGroupId?: string;
    amountCents?: number;
    amountCurrency?: string;
    vatAmountCents?: number;
    vatAmountCurrency?: string;
    units?: number;
    eventsCount?: number;
    item?: LagoApi.FeeItem;
}
