/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InvoiceType = "charge" | "add_on" | "subscription" | "credit";

export const InvoiceType = {
    Charge: "charge",
    AddOn: "add_on",
    Subscription: "subscription",
    Credit: "credit",
} as const;
