/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PlanInterval = "weekly" | "monthly" | "yearly";

export const PlanInterval = {
    Weekly: "weekly",
    Monthly: "monthly",
    Yearly: "yearly",
} as const;
