/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RefundStatus = "pending" | "succeeded" | "failed";

export const RefundStatus = {
    Pending: "pending",
    Succeeded: "succeeded",
    Failed: "failed",
} as const;
