/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Status = "active" | "terminated";

export const Status = {
    Active: "active",
    Terminated: "terminated",
} as const;
