/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SubscriptionStatus = "active" | "pending" | "terminated" | "canceled";

export const SubscriptionStatus = {
    Active: "active",
    Pending: "pending",
    Terminated: "terminated",
    Canceled: "canceled",
} as const;
