/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LagoApi } from "@fern-api/lago";

export interface SubscriptionObject {
    lagoId?: string;
    externalId?: string;
    lagoCustomerId?: string;
    externalCustomerId?: string;
    name?: string;
    planCode?: string;
    status?: LagoApi.SubscriptionStatus;
    billingTime?: LagoApi.BillingTime;
    subscriptionAt?: string;
    startedAt?: string;
    terminatedAt?: string;
    canceledAt?: string;
    createdAt?: string;
    previousPlanCode?: string;
    nextPlanCode?: string;
    downgradePlanDate?: string;
}
