/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TransactionType = "inbound" | "outbound";

export const TransactionType = {
    Inbound: "inbound",
    Outbound: "outbound",
} as const;
