/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const AppliedCouponInputObject: core.serialization.ObjectSchema<
    serializers.AppliedCouponInputObject.Raw,
    LagoApi.AppliedCouponInputObject
> = core.serialization.object({
    externalCustomerId: core.serialization.property("external_customer_id", core.serialization.string().optional()),
    couponCode: core.serialization.property("coupon_code", core.serialization.string().optional()),
    frequency: core.serialization.lazy(async () => (await import("../../..")).FrequencyType).optional(),
    frequencyDuration: core.serialization.property("frequency_duration", core.serialization.number().optional()),
    amountCents: core.serialization.property("amount_cents", core.serialization.number().optional()),
    amountCurrency: core.serialization.property("amount_currency", core.serialization.string().optional()),
    percentageRate: core.serialization.property("percentage_rate", core.serialization.number().optional()),
});

export declare namespace AppliedCouponInputObject {
    interface Raw {
        external_customer_id?: string | null;
        coupon_code?: string | null;
        frequency?: serializers.FrequencyType.Raw | null;
        frequency_duration?: number | null;
        amount_cents?: number | null;
        amount_currency?: string | null;
        percentage_rate?: number | null;
    }
}
