/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const AppliedCoupon: core.serialization.ObjectSchema<serializers.AppliedCoupon.Raw, LagoApi.AppliedCoupon> =
    core.serialization.object({
        appliedCoupon: core.serialization.property(
            "applied_coupon",
            core.serialization.lazyObject(async () => (await import("../../..")).AppliedCouponObject).optional()
        ),
    });

export declare namespace AppliedCoupon {
    interface Raw {
        applied_coupon?: serializers.AppliedCouponObject.Raw | null;
    }
}
