/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const AppliedCouponInput: core.serialization.ObjectSchema<
    serializers.AppliedCouponInput.Raw,
    LagoApi.AppliedCouponInput
> = core.serialization.object({
    appliedCoupon: core.serialization.property(
        "applied_coupon",
        core.serialization.lazyObject(async () => (await import("../../..")).AppliedCouponInputObject).optional()
    ),
});

export declare namespace AppliedCouponInput {
    interface Raw {
        applied_coupon?: serializers.AppliedCouponInputObject.Raw | null;
    }
}
