/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const AppliedCouponObject: core.serialization.ObjectSchema<
    serializers.AppliedCouponObject.Raw,
    LagoApi.AppliedCouponObject
> = core.serialization.object({
    lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
    lagoCouponId: core.serialization.property("lago_coupon_id", core.serialization.string().optional()),
    couponCode: core.serialization.property("coupon_code", core.serialization.string().optional()),
    lagoCustomerId: core.serialization.property("lago_customer_id", core.serialization.string().optional()),
    externalCustomerId: core.serialization.property("external_customer_id", core.serialization.string().optional()),
    status: core.serialization.lazy(async () => (await import("../../..")).CouponStatus).optional(),
    amountCents: core.serialization.property("amount_cents", core.serialization.number().optional()),
    amountCentsRemaining: core.serialization.property("amount_cents_remaining", core.serialization.number().optional()),
    amountCurrency: core.serialization.property("amount_currency", core.serialization.string().optional()),
    percentageRate: core.serialization.property("percentage_rate", core.serialization.number().optional()),
    frequency: core.serialization.lazy(async () => (await import("../../..")).FrequencyType).optional(),
    frequencyDuration: core.serialization.property("frequency_duration", core.serialization.number().optional()),
    frequencyDurationRemaining: core.serialization.property(
        "frequency_duration_remaining",
        core.serialization.number().optional()
    ),
    expirationAt: core.serialization.property("expiration_at", core.serialization.string().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    terminatedAt: core.serialization.property("terminated_at", core.serialization.string().optional()),
});

export declare namespace AppliedCouponObject {
    interface Raw {
        lago_id?: string | null;
        lago_coupon_id?: string | null;
        coupon_code?: string | null;
        lago_customer_id?: string | null;
        external_customer_id?: string | null;
        status?: serializers.CouponStatus.Raw | null;
        amount_cents?: number | null;
        amount_cents_remaining?: number | null;
        amount_currency?: string | null;
        percentage_rate?: number | null;
        frequency?: serializers.FrequencyType.Raw | null;
        frequency_duration?: number | null;
        frequency_duration_remaining?: number | null;
        expiration_at?: string | null;
        created_at?: string | null;
        terminated_at?: string | null;
    }
}
