/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const AppliedCoupons: core.serialization.ObjectSchema<serializers.AppliedCoupons.Raw, LagoApi.AppliedCoupons> =
    core.serialization.object({
        appliedCoupons: core.serialization.property(
            "applied_coupons",
            core.serialization
                .list(core.serialization.lazyObject(async () => (await import("../../..")).AppliedCouponObject))
                .optional()
        ),
    });

export declare namespace AppliedCoupons {
    interface Raw {
        applied_coupons?: serializers.AppliedCouponObject.Raw[] | null;
    }
}
