/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CouponInput: core.serialization.ObjectSchema<serializers.CouponInput.Raw, LagoApi.CouponInput> =
    core.serialization.object({
        coupon: core.serialization.lazyObject(async () => (await import("../../..")).CouponInputObject).optional(),
    });

export declare namespace CouponInput {
    interface Raw {
        coupon?: serializers.CouponInputObject.Raw | null;
    }
}
