/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CouponStatus: core.serialization.Schema<serializers.CouponStatus.Raw, LagoApi.CouponStatus> =
    core.serialization.enum_(["active", "terminated"]);

export declare namespace CouponStatus {
    type Raw = "active" | "terminated";
}
