/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const ExpirationType: core.serialization.Schema<serializers.ExpirationType.Raw, LagoApi.ExpirationType> =
    core.serialization.enum_(["no_expiration", "time_limit"]);

export declare namespace ExpirationType {
    type Raw = "no_expiration" | "time_limit";
}
