/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const AddOnInput: core.serialization.ObjectSchema<serializers.AddOnInput.Raw, LagoApi.AddOnInput> =
    core.serialization.object({
        addOn: core.serialization.property(
            "add_on",
            core.serialization.lazyObject(async () => (await import("../../..")).AddOnInputObject).optional()
        ),
    });

export declare namespace AddOnInput {
    interface Raw {
        add_on?: serializers.AddOnInputObject.Raw | null;
    }
}
