/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const AddOnObject: core.serialization.ObjectSchema<serializers.AddOnObject.Raw, LagoApi.AddOnObject> =
    core.serialization.object({
        lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
        name: core.serialization.string().optional(),
        code: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
        amountCents: core.serialization.property("amount_cents", core.serialization.number().optional()),
        amountCurrency: core.serialization.property("amount_currency", core.serialization.string().optional()),
    });

export declare namespace AddOnObject {
    interface Raw {
        lago_id?: string | null;
        name?: string | null;
        code?: string | null;
        description?: string | null;
        created_at?: string | null;
        amount_cents?: number | null;
        amount_currency?: string | null;
    }
}
