/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const AggregationType: core.serialization.Schema<serializers.AggregationType.Raw, LagoApi.AggregationType> =
    core.serialization.enum_(["count_agg", "sum_agg", "max_agg", "unique_count_agg", "recurring_count_agg"]);

export declare namespace AggregationType {
    type Raw = "count_agg" | "sum_agg" | "max_agg" | "unique_count_agg" | "recurring_count_agg";
}
