/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const BillableMetricObject: core.serialization.ObjectSchema<
    serializers.BillableMetricObject.Raw,
    LagoApi.BillableMetricObject
> = core.serialization.object({
    lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
    name: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    fieldName: core.serialization.property("field_name", core.serialization.string().optional()),
    aggregationType: core.serialization.property(
        "aggregation_type",
        core.serialization.lazy(async () => (await import("../../..")).AggregationType).optional()
    ),
    group: core.serialization.lazyObject(async () => (await import("../../..")).BillableMetricGroup).optional(),
    activeSubscriptionsCount: core.serialization.property(
        "active_subscriptions_count",
        core.serialization.number().optional()
    ),
    draftInvoicesCount: core.serialization.property("draft_invoices_count", core.serialization.number().optional()),
});

export declare namespace BillableMetricObject {
    interface Raw {
        lago_id?: string | null;
        name?: string | null;
        code?: string | null;
        description?: string | null;
        created_at?: string | null;
        field_name?: string | null;
        aggregation_type?: serializers.AggregationType.Raw | null;
        group?: serializers.BillableMetricGroup.Raw | null;
        active_subscriptions_count?: number | null;
        draft_invoices_count?: number | null;
    }
}
