/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const BillableMetricInput: core.serialization.ObjectSchema<
    serializers.BillableMetricInput.Raw,
    LagoApi.BillableMetricInput
> = core.serialization.object({
    billableMetric: core.serialization.property(
        "billable_metric",
        core.serialization.lazyObject(async () => (await import("../../..")).BillableMetricInputObject).optional()
    ),
});

export declare namespace BillableMetricInput {
    interface Raw {
        billable_metric?: serializers.BillableMetricInputObject.Raw | null;
    }
}
