/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Charge: core.serialization.ObjectSchema<serializers.Charge.Raw, LagoApi.Charge> =
    core.serialization.object({
        lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
        chargeModel: core.serialization.property(
            "charge_model",
            core.serialization.lazy(async () => (await import("../../..")).ChargeModelType).optional()
        ),
    });

export declare namespace Charge {
    interface Raw {
        lago_id?: string | null;
        charge_model?: serializers.ChargeModelType.Raw | null;
    }
}
