/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const ChargeModel: core.serialization.Schema<serializers.ChargeModel.Raw, LagoApi.ChargeModel> =
    core.serialization.enum_(["standard", "graduated", "package", "percentage", "volume"]);

export declare namespace ChargeModel {
    type Raw = "standard" | "graduated" | "package" | "percentage" | "volume";
}
