/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CouponType: core.serialization.Schema<serializers.CouponType.Raw, LagoApi.CouponType> =
    core.serialization.enum_(["fixed_amount", "percentage"]);

export declare namespace CouponType {
    type Raw = "fixed_amount" | "percentage";
}
