/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CreditItem: core.serialization.ObjectSchema<serializers.CreditItem.Raw, LagoApi.CreditItem> =
    core.serialization.object({
        lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
        type: core.serialization.string().optional(),
        code: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
    });

export declare namespace CreditItem {
    interface Raw {
        lago_id?: string | null;
        type?: string | null;
        code?: string | null;
        name?: string | null;
    }
}
