/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CreditReason: core.serialization.Schema<serializers.CreditReason.Raw, LagoApi.CreditReason> =
    core.serialization.enum_([
        "duplicated_charge",
        "product_unsatisfactory",
        "order_change",
        "order_cancellation",
        "fraudulent_charge",
        "other",
    ]);

export declare namespace CreditReason {
    type Raw =
        | "duplicated_charge"
        | "product_unsatisfactory"
        | "order_change"
        | "order_cancellation"
        | "fraudulent_charge"
        | "other";
}
