/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CreditObject: core.serialization.ObjectSchema<serializers.CreditObject.Raw, LagoApi.CreditObject> =
    core.serialization.object({
        lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
        amountCents: core.serialization.property("amount_cents", core.serialization.number().optional()),
        amountCurrency: core.serialization.property("amount_currency", core.serialization.string().optional()),
        item: core.serialization.lazyObject(async () => (await import("../../..")).CreditItem).optional(),
    });

export declare namespace CreditObject {
    interface Raw {
        lago_id?: string | null;
        amount_cents?: number | null;
        amount_currency?: string | null;
        item?: serializers.CreditItem.Raw | null;
    }
}
