/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const CustomerUsageObject: core.serialization.ObjectSchema<
    serializers.CustomerUsageObject.Raw,
    LagoApi.CustomerUsageObject
> = core.serialization.object({
    fromDatetime: core.serialization.property("from_datetime", core.serialization.string().optional()),
    toDatetime: core.serialization.property("to_datetime", core.serialization.string().optional()),
    issuingDate: core.serialization.property("issuing_date", core.serialization.string().optional()),
    amountCents: core.serialization.property("amount_cents", core.serialization.number().optional()),
    amountCurrency: core.serialization.property("amount_currency", core.serialization.string().optional()),
    totalAmountCents: core.serialization.property("total_amount_cents", core.serialization.number().optional()),
    totalAmountCurrency: core.serialization.property("total_amount_currency", core.serialization.string().optional()),
    vatAmountCents: core.serialization.property("vat_amount_cents", core.serialization.number().optional()),
    vatAmountCurrency: core.serialization.property("vat_amount_currency", core.serialization.string().optional()),
    chargesUsage: core.serialization.property(
        "charges_usage",
        core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).ChargeUsageObject))
            .optional()
    ),
});

export declare namespace CustomerUsageObject {
    interface Raw {
        from_datetime?: string | null;
        to_datetime?: string | null;
        issuing_date?: string | null;
        amount_cents?: number | null;
        amount_currency?: string | null;
        total_amount_cents?: number | null;
        total_amount_currency?: string | null;
        vat_amount_cents?: number | null;
        vat_amount_currency?: string | null;
        charges_usage?: serializers.ChargeUsageObject.Raw[] | null;
    }
}
