/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const FeeItem: core.serialization.ObjectSchema<serializers.FeeItem.Raw, LagoApi.FeeItem> =
    core.serialization.object({
        type: core.serialization.lazy(async () => (await import("../../..")).BillingTime).optional(),
        code: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
    });

export declare namespace FeeItem {
    interface Raw {
        type?: serializers.BillingTime.Raw | null;
        code?: string | null;
        name?: string | null;
    }
}
