/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Group: core.serialization.ObjectSchema<serializers.Group.Raw, LagoApi.Group> = core.serialization.object({
    lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
    key: core.serialization.string().optional(),
    value: core.serialization.string().optional(),
    units: core.serialization.number().optional(),
    amountCents: core.serialization.property("amount_cents", core.serialization.number().optional()),
});

export declare namespace Group {
    interface Raw {
        lago_id?: string | null;
        key?: string | null;
        value?: string | null;
        units?: number | null;
        amount_cents?: number | null;
    }
}
