/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Plan: core.serialization.ObjectSchema<serializers.Plan.Raw, LagoApi.Plan> = core.serialization.object({
    plan: core.serialization.lazyObject(async () => (await import("../../..")).PlanObject).optional(),
});

export declare namespace Plan {
    interface Raw {
        plan?: serializers.PlanObject.Raw | null;
    }
}
