/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Status: core.serialization.Schema<serializers.Status.Raw, LagoApi.Status> = core.serialization.enum_([
    "active",
    "terminated",
]);

export declare namespace Status {
    type Raw = "active" | "terminated";
}
