/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const SubscriptionObject: core.serialization.ObjectSchema<
    serializers.SubscriptionObject.Raw,
    LagoApi.SubscriptionObject
> = core.serialization.object({
    lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
    externalId: core.serialization.property("external_id", core.serialization.string().optional()),
    lagoCustomerId: core.serialization.property("lago_customer_id", core.serialization.string().optional()),
    externalCustomerId: core.serialization.property("external_customer_id", core.serialization.string().optional()),
    name: core.serialization.string().optional(),
    planCode: core.serialization.property("plan_code", core.serialization.string().optional()),
    status: core.serialization.lazy(async () => (await import("../../..")).SubscriptionStatus).optional(),
    billingTime: core.serialization.property(
        "billing_time",
        core.serialization.lazy(async () => (await import("../../..")).BillingTime).optional()
    ),
    subscriptionAt: core.serialization.property("subscription_at", core.serialization.string().optional()),
    startedAt: core.serialization.property("started_at", core.serialization.string().optional()),
    terminatedAt: core.serialization.property("terminated_at", core.serialization.string().optional()),
    canceledAt: core.serialization.property("canceled_at", core.serialization.string().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    previousPlanCode: core.serialization.property("previous_plan_code", core.serialization.string().optional()),
    nextPlanCode: core.serialization.property("next_plan_code", core.serialization.string().optional()),
    downgradePlanDate: core.serialization.property("downgrade_plan_date", core.serialization.string().optional()),
});

export declare namespace SubscriptionObject {
    interface Raw {
        lago_id?: string | null;
        external_id?: string | null;
        lago_customer_id?: string | null;
        external_customer_id?: string | null;
        name?: string | null;
        plan_code?: string | null;
        status?: serializers.SubscriptionStatus.Raw | null;
        billing_time?: serializers.BillingTime.Raw | null;
        subscription_at?: string | null;
        started_at?: string | null;
        terminated_at?: string | null;
        canceled_at?: string | null;
        created_at?: string | null;
        previous_plan_code?: string | null;
        next_plan_code?: string | null;
        downgrade_plan_date?: string | null;
    }
}
