/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const Wallet: core.serialization.ObjectSchema<serializers.Wallet.Raw, LagoApi.Wallet> =
    core.serialization.object({
        wallet: core.serialization.lazyObject(async () => (await import("../../..")).WalletObject).optional(),
    });

export declare namespace Wallet {
    interface Raw {
        wallet?: serializers.WalletObject.Raw | null;
    }
}
