/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const WalletObject: core.serialization.ObjectSchema<serializers.WalletObject.Raw, LagoApi.WalletObject> =
    core.serialization.object({
        lagoId: core.serialization.property("lago_id", core.serialization.string().optional()),
        lagoCustomerId: core.serialization.property("lago_customer_id", core.serialization.string().optional()),
        externalCustomerId: core.serialization.property("external_customer_id", core.serialization.string().optional()),
        status: core.serialization.lazy(async () => (await import("../../..")).WalletStatus).optional(),
        currency: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
        rateAmount: core.serialization.property("rate_amount", core.serialization.number().optional()),
        creditsBalance: core.serialization.property("credits_balance", core.serialization.number().optional()),
        balance: core.serialization.number().optional(),
        consumedCredits: core.serialization.property("consumed_credits", core.serialization.number().optional()),
        createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
        expirationAt: core.serialization.property("expiration_at", core.serialization.string().optional()),
        lastBalanceSyncAt: core.serialization.property("last_balance_sync_at", core.serialization.string().optional()),
        lastConsumedCreditAt: core.serialization.property(
            "last_consumed_credit_at",
            core.serialization.string().optional()
        ),
        terminatedAt: core.serialization.property("terminated_at", core.serialization.string().optional()),
    });

export declare namespace WalletObject {
    interface Raw {
        lago_id?: string | null;
        lago_customer_id?: string | null;
        external_customer_id?: string | null;
        status?: serializers.WalletStatus.Raw | null;
        currency?: string | null;
        name?: string | null;
        rate_amount?: number | null;
        credits_balance?: number | null;
        balance?: number | null;
        consumed_credits?: number | null;
        created_at?: string | null;
        expiration_at?: string | null;
        last_balance_sync_at?: string | null;
        last_consumed_credit_at?: string | null;
        terminated_at?: string | null;
    }
}
