/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const WalletTransactions: core.serialization.ObjectSchema<
    serializers.WalletTransactions.Raw,
    LagoApi.WalletTransactions
> = core.serialization.object({
    walletTransactions: core.serialization.property(
        "wallet_transactions",
        core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).WalletTransactionObject))
            .optional()
    ),
});

export declare namespace WalletTransactions {
    interface Raw {
        wallet_transactions?: serializers.WalletTransactionObject.Raw[] | null;
    }
}
