/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LagoApi } from "@fern-api/lago";
import * as core from "../../../../core";

export const WalletStatus: core.serialization.Schema<serializers.WalletStatus.Raw, LagoApi.WalletStatus> =
    core.serialization.enum_(["active", "terminated"]);

export declare namespace WalletStatus {
    type Raw = "active" | "terminated";
}
